//Auth
export const SET_TOKENS = "SET_TOKENS";
export const LOGOUT = "LOGOUT";

//Register
export const SET_REGISTER_NAME = 'SET_REGISTER_NAME';

//Home
export const SET_EXAMS_LIST_LIVE = 'SET_EXAMS_LIST_LIVE';
export const SET_EXAMS_LIST_PRACTICE = 'SET_EXAMS_LIST_PRACTICE';
export const SET_COURSESS_LIST = 'SET_COURSESS_LIST';

//Exam
export const SET_EXAM_LIST = 'SET_EXAM_LIST';
export const SET_EXAM_DETAILS = 'SET_EXAM_DETAILS';
export const SET_TAKE_EXAM_DETAILS = 'SET_TAKE_EXAM_DETAILS';
export const SUBMIT_EXAM = 'SUBMIT_EXAM';